### ISSUE TITLE
If you want a profile README, you should make a repository named 'isAnshTHEmaN' so it's under isAnshTHEmaN/isAnshTHEmaN and initialize with a README.md in the repository creating stages.

### ISSUE THREAD

**Issue by intrepidbird** [isAnshTHEmaN/hello-world#2]
You can also make the file after you make the repo

**Comment by intrepidbird** [comment]
You can follow the official GitHub instructions [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme).

It's also recommended you learn a bit of [markdown syntax](https://www.markdownguide.org/basic-syntax/). It's easy (trust).

**Comment by intrepidbird** [comment]
The link should be https://github.com/isAnshTHEmaN/isAnshTHEmaN/blob/main/README.md when you're done.

**Comment by Anshuman-Roy-22** [comment]
Thank you

**Comment by Anshuman-Roy-22** [comment]
Fixed it: https://github.com/isAnshTHEmaN

**Comment by intrepidbird** [comment]
Nice!
